# Autogenerated by `bun2nix`, editing manually is not recommended
#
# Set of Bun packages to install
#
# Consume this with `fetchBunDeps` (recommended)
# or `pkgs.callPackage` if you wish to handle
# it manually.
{
  copyPathToStore,
  fetchFromGitHub,
  fetchgit,
  fetchurl,
  ...
}:
{
  "@discordjs/builders@1.11.3" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/builders/-/builders-1.11.3.tgz";
    hash = "sha512-p3kf5eV49CJiRTfhtutUCeivSyQ/l2JlKodW1ZquRwwvlOWmG9+6jFShX6x8rUiYhnP6wKI96rgN/SXMy5e5aw==";
  };
  "@discordjs/collection@1.5.3" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/collection/-/collection-1.5.3.tgz";
    hash = "sha512-SVb428OMd3WO1paV3rm6tSjM4wC+Kecaa1EUGX7vc6/fddvw/6lg90z4QtCqm21zvVe92vMMDt9+DkIvjXImQQ==";
  };
  "@discordjs/collection@2.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/collection/-/collection-2.1.1.tgz";
    hash = "sha512-LiSusze9Tc7qF03sLCujF5iZp7K+vRNEDBZ86FT9aQAv3vxMLihUvKvpsCWiQ2DJq1tVckopKm1rxomgNUc9hg==";
  };
  "@discordjs/formatters@0.6.1" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/formatters/-/formatters-0.6.1.tgz";
    hash = "sha512-5cnX+tASiPCqCWtFcFslxBVUaCetB0thvM/JyavhbXInP1HJIEU+Qv/zMrnuwSsX3yWH2lVXNJZeDK3EiP4HHg==";
  };
  "@discordjs/rest@2.6.0" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/rest/-/rest-2.6.0.tgz";
    hash = "sha512-RDYrhmpB7mTvmCKcpj+pc5k7POKszS4E2O9TYc+U+Y4iaCP+r910QdO43qmpOja8LRr1RJ0b3U+CqVsnPqzf4w==";
  };
  "@discordjs/util@1.1.1" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/util/-/util-1.1.1.tgz";
    hash = "sha512-eddz6UnOBEB1oITPinyrB2Pttej49M9FZQY8NxgEvc3tq6ZICZ19m70RsmzRdDHk80O9NoYN/25AqJl8vPVf/g==";
  };
  "@discordjs/ws@1.2.3" = fetchurl {
    url = "https://registry.npmjs.org/@discordjs/ws/-/ws-1.2.3.tgz";
    hash = "sha512-wPlQDxEmlDg5IxhJPuxXr3Vy9AjYq5xCvFWGJyD7w7Np8ZGu+Mc+97LCoEc/+AYCo2IDpKioiH0/c/mj5ZR9Uw==";
  };
  "@sapphire/async-queue@1.5.5" = fetchurl {
    url = "https://registry.npmjs.org/@sapphire/async-queue/-/async-queue-1.5.5.tgz";
    hash = "sha512-cvGzxbba6sav2zZkH8GPf2oGk9yYoD5qrNWdu9fRehifgnFZJMV+nuy2nON2roRO4yQQ+v7MK/Pktl/HgfsUXg==";
  };
  "@sapphire/shapeshift@4.0.0" = fetchurl {
    url = "https://registry.npmjs.org/@sapphire/shapeshift/-/shapeshift-4.0.0.tgz";
    hash = "sha512-d9dUmWVA7MMiKobL3VpLF8P2aeanRTu6ypG2OIaEv/ZHH/SUQ2iHOVyi5wAPjQ+HmnMuL0whK9ez8I/raWbtIg==";
  };
  "@sapphire/snowflake@3.5.3" = fetchurl {
    url = "https://registry.npmjs.org/@sapphire/snowflake/-/snowflake-3.5.3.tgz";
    hash = "sha512-jjmJywLAFoWeBi1W7994zZyiNWPIiqRRNAmSERxyg93xRGzNYvGjlZ0gR6x0F4gPRi2+0O6S71kOZYyr3cxaIQ==";
  };
  "@types/node@24.3.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/node/-/node-24.3.1.tgz";
    hash = "sha512-3vXmQDXy+woz+gnrTvuvNrPzekOi+Ds0ReMxw0LzBiK3a+1k0kQn9f2NWk+lgD4rJehFUmYy2gMhJ2ZI+7YP9g==";
  };
  "@types/ws@8.18.1" = fetchurl {
    url = "https://registry.npmjs.org/@types/ws/-/ws-8.18.1.tgz";
    hash = "sha512-ThVF6DCVhA8kUGy+aazFQ4kXQ7E1Ty7A3ypFOe0IcJV8O/M511G99AW24irKrW56Wt44yG9+ij8FaqoBGkuBXg==";
  };
  "@vladfrangu/async_event_emitter@2.4.6" = fetchurl {
    url = "https://registry.npmjs.org/@vladfrangu/async_event_emitter/-/async_event_emitter-2.4.6.tgz";
    hash = "sha512-RaI5qZo6D2CVS6sTHFKg1v5Ohq/+Bo2LZ5gzUEwZ/WkHhwtGTCB/sVLw8ijOkAUxasZ+WshN/Rzj4ywsABJ5ZA==";
  };
  "discord-api-types@0.38.23" = fetchurl {
    url = "https://registry.npmjs.org/discord-api-types/-/discord-api-types-0.38.23.tgz";
    hash = "sha512-C8VjK0yxBUq1dakxGpUXQm4VSC7R+aaD2SIr3paj2a0bP/LRok1AqHiezp30GruK6Ba9FtQAKqYUMJPzsqv7IQ==";
  };
  "discord.js@14.22.1" = fetchurl {
    url = "https://registry.npmjs.org/discord.js/-/discord.js-14.22.1.tgz";
    hash = "sha512-3k+Kisd/v570Jr68A1kNs7qVhNehDwDJAPe4DZ2Syt+/zobf9zEcuYFvsfIaAOgCa0BiHMfOOKQY4eYINl0z7w==";
  };
  "fast-deep-equal@3.1.3" = fetchurl {
    url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
    hash = "sha512-f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
  };
  "lodash.snakecase@4.1.1" = fetchurl {
    url = "https://registry.npmjs.org/lodash.snakecase/-/lodash.snakecase-4.1.1.tgz";
    hash = "sha512-QZ1d4xoBHYUeuouhEq3lk3Uq7ldgyFXGBhg04+oRLnIz8o9T65Eh+8YdroUwn846zchkA9yDsDl5CVVaV2nqYw==";
  };
  "lodash@4.17.21" = fetchurl {
    url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
    hash = "sha512-v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
  };
  "magic-bytes.js@1.12.1" = fetchurl {
    url = "https://registry.npmjs.org/magic-bytes.js/-/magic-bytes.js-1.12.1.tgz";
    hash = "sha512-ThQLOhN86ZkJ7qemtVRGYM+gRgR8GEXNli9H/PMvpnZsE44Xfh3wx9kGJaldg314v85m+bFW6WBMaVHJc/c3zA==";
  };
  "ts-mixer@6.0.4" = fetchurl {
    url = "https://registry.npmjs.org/ts-mixer/-/ts-mixer-6.0.4.tgz";
    hash = "sha512-ufKpbmrugz5Aou4wcr5Wc1UUFWOLhq+Fm6qa6P0w0K5Qw2yhaUoiWszhCVuNQyNwrlGiscHOmqYoAox1PtvgjA==";
  };
  "tslib@2.8.1" = fetchurl {
    url = "https://registry.npmjs.org/tslib/-/tslib-2.8.1.tgz";
    hash = "sha512-oJFu94HQb+KVduSUQL7wnpmqnfmLsOA/nAh6b6EH0wCEoK0/mPeXU6c3wKDV83MkOuHPRHtSXKKU99IBazS/2w==";
  };
  "undici-types@7.10.0" = fetchurl {
    url = "https://registry.npmjs.org/undici-types/-/undici-types-7.10.0.tgz";
    hash = "sha512-t5Fy/nfn+14LuOc2KNYg75vZqClpAiqscVvMygNnlsHBFpSXdJaYtXMcdNLpl/Qvc3P2cB3s6lOV51nqsFq4ag==";
  };
  "undici@6.21.3" = fetchurl {
    url = "https://registry.npmjs.org/undici/-/undici-6.21.3.tgz";
    hash = "sha512-gBLkYIlEnSp8pFbT64yFgGE6UIB9tAkhukC23PmMDCe5Nd+cRqKxSjw5y54MK2AZMgZfJWMaNE4nYUHgi1XEOw==";
  };
  "ws@8.18.3" = fetchurl {
    url = "https://registry.npmjs.org/ws/-/ws-8.18.3.tgz";
    hash = "sha512-PEIGCY5tSlUt50cqyMXfCzX+oOPqN0vuGqWzbcJ2xvnkzkq46oOpz7dQaTDBdfICb4N14+GARUDw2XV2N4tvzg==";
  };
}
