name: Deploy IdeaLync (Local runner)

on:
    push:
        branches:
            - deploy

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Create .env file
              run: |
                  echo "APP_DISCORD_TOKEN=${{ secrets.APP_DISCORD_TOKEN }}" >> .env
                  echo "ROLE_CHANNEL_ID=${{ secrets.ROLE_CHANNEL_ID }}" >> .env
                  echo "MEMBER_ID=${{ secrets.MEMBER_ID }}" >> .env
                  echo "OBSERVER_ID=${{ secrets.OBSERVER_ID }}" >> .env
                  echo "IDEA_CHANNEL_ID=${{ secrets.IDEA_CHANNEL_ID }}" >> .env
                  echo "PITCHING_BOARD_FORUM_ID=${{ secrets.PITCHING_BOARD_FORUM_ID }}" >> .env
                  echo "PROJECT_BOARD_FORUM_ID=${{ secrets.PROJECT_BOARD_FORUM_ID }}" >> .env
                  echo "BRAINSTORMING_TAG_ID=${{ secrets.BRAINSTORMING_TAG_ID }}" >> .env
                  echo "HELP_WANTED_TAG_ID=${{ secrets.HELP_WANTED_TAG_ID }}" >> .env
                  echo "PENDING_TAG_ID=${{ secrets.PENDING_TAG_ID }}" >> .env
                  echo "MEETING_VOICE_CHANNEL_ID=${{ secrets.MEETING_VOICE_CHANNEL_ID }}" >> .env
                  echo "MEETING_ANNOUNCE_ID=${{ secrets.MEETING_ANNOUNCE_ID }}" >> .env

            - name: Build and Run Docker Container Locally
              run: |
                  docker build -t idealync-bot:deploy .
                  docker stop idealync-bot-deploy || true
                  docker rm idealync-bot-deploy || true
                  docker run -d \
                    --name idealync-bot-deploy \
                    --env-file .env \
                    --restart unless-stopped \
                    idealync-bot:deploy
